# Generated by Django 2.2.5 on 2020-08-06 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Último nome')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('status', models.IntegerField(choices=[(1, 'Criado'), (2, 'Pago'), (3, 'Entregue'), (4, 'Cancelado')], default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
